//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silversite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homesell.CSharp._Silversite.Services.Common.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir or Madam.
        /// </summary>
        internal static string CompanySalutation {
            get {
                return ResourceManager.GetString("CompanySalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Ms.
        /// </summary>
        internal static string FemaleSalutation {
            get {
                return ResourceManager.GetString("FemaleSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string FemaleTitle {
            get {
                return ResourceManager.GetString("FemaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir or Madam.
        /// </summary>
        internal static string GroupSalutation {
            get {
                return ResourceManager.GetString("GroupSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GroupTitle {
            get {
                return ResourceManager.GetString("GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Mr.
        /// </summary>
        internal static string MaleSalutation {
            get {
                return ResourceManager.GetString("MaleSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string MaleTitle {
            get {
                return ResourceManager.GetString("MaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Miss.
        /// </summary>
        internal static string MissSalutation {
            get {
                return ResourceManager.GetString("MissSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        internal static string MissTitle {
            get {
                return ResourceManager.GetString("MissTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir or Madam.
        /// </summary>
        internal static string NoneSalutation {
            get {
                return ResourceManager.GetString("NoneSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoneTitle {
            get {
                return ResourceManager.GetString("NoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to unsubscribe from this newsletter..
        /// </summary>
        internal static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
    }
}
