// <auto-generated />
namespace Silversite.EntityTest.Cats
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Cats_v10 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205031550171_Cats_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVXzW7bMAy+D9g7GD5th1ppBhRt4bTokmYItjRF3fWu2HQiTJI9Sy6SZ9thj7RXGOX/2Plpul52CWKaIj9+/kjaf379dq9XglvPkCgWyYF96vRsC6QfBUwuBnaqw5Nz+/rq/Tv3NhAr66n06xs/PCnVwF5qHV8SovwlCKocwfwkUlGoHT8ShAYR6fd65+S0RwBD2BjLstyHVGomILvAy2EkfYh1Svk0CoCrwo53vCyqdUcFqJj6MLA9xjO4GpxbDKLXj6C0M2WLhGrEpmzrhjOKuDzg4ZEgexcGpF2lRwBFjnUMGYiBPaS66YAuX2G9YUDTfRLFkOj1A4TFMXSyLXLYz/y2HV3STlEdbEY3IAf2ROpPfdu6Szmnc46GkHKFIeOzS09HCXwBCUgVBPdUa0jwYU4CyIosyLqMz17G1wXp9Q1fhEoZ6Yz9DvIWzry6HKinExSZbY3ZCoJvIBd6WYGd0lVpOe2f29Z3yVCTeEgnKWwpbn/WYcSj5Mi0+HdP2vy6mdUltVK6+kGBa8qQ+FpExgSrtpZydw907YiKrkPnsnaMCLemrxLVLUTyHip7jexoNndK4xiZaTRfYbG8vPOGJ97x/STyGMRXW9qqQltlQoXSBbTumicYwJglSo+opnNqntUwEF23g7SWiRrstnuyJrt0Nv/zA4eGj9OZDk0ix1ibwF7LyoQK05aZUpzzfMppsq3XUdKpkHtGy+7zeQ82A2ybOfsiFP3UDFGYujFc0iq+TTfp8N2afe1nt0/1bZcqe6X+lsrdQnGH905HgrmLbSE5zyww8vPWSoNwjIPj/eRDzrDe2mFKJQtRL4/RDzA7FDvk9cuqGr5KBfz/3ljMkHRwNx0585ubRj7TxF/SpLtX/mWRlFE/CLr6+KbLoTPsDu6IXSsi12hzbtVjC+vI8eY75pXbpNs/Lmm+3bkjUGxRhzDvehJ8My3roKXPRIZRSTnW10RUurSeyBQ0DZCmm0SzkPoab/ugVLbhnyhP0eVWzCGYyFmq41TfKAVizjeU7ZL9+bOVuYnZncXZvH+LEhAmwxJgJj+njAcV7nFXkbtCGMUUvYOo8A0Hwy3WVaS7SL4wUEHfCGKQpvMeQcQcg6mZ9Ogz7MZ2mMNNxtwRo7g0RZPB3FIg8ShmbqTABM0TdT7zcULM18nVX4yfPYXPDAAA"; }
        }
    }
}
