// <auto-generated />
namespace Silversite.EntityTest.Cars
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Cars_v10 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205031550015_Cars_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WS27bMBTcF+gdBO4jOm4RJIGcILXjwmgdB1GaPS0920RJShUpwz5bFz1Sr9BH/S3ZcRJk0Z1Evc9w3nDEv7//eNcbKZw1JJpHakBO3R5xQAVRyNVyQFKzODkn11cfP3i3odw4T2Vc38ZhptIDsjImvqRUByuQTLuSB0mko4Vxg0hSFka03+ud09MeBSxBsJbjeA+pMlxC9oKvw0gFEJuUiWkUgtDFOn7xs6rOHZOgYxbAgPhcZHANuLdYxGwfQRt3ypcJM4hNE+dGcIa4fBCLV4LsXViQpGqPAIoe2xgyEAMyZEkzAEO+wXZnAZfukyiGxGwfYFGkYRBx6G4ibWdWec0k23tAJsp86hPnLhWCzQUuLJjQQJz47NI3UQJfQQEyAOE9MwYSnNEkhAx7wcFlfPYyGi5or29poEypyGSkdpC3cGZTK5H6JkHxEGfMNxB+B7U0qwrtlG3KlbPPxPmhOEoNc0ySQnNz+XuzqUfrSXTngwIyjCMD9ZDsEmxMa1Z5uA+mDkTF1KVz2bh2yHvbV41qidJco6WW6QExe1MWx0hMQ9zFiuPnyh6e+K/Xq8xr0EDvkW2FtuqEUmFLaH3F1oh0zBNtRsywObOjGoayG3aU1rJRg9322ajJLoPtc55w7HC7ndPXJHKMe5Mo+mybUGHac2aLPD9ggiX7Dt0wEqlUB4/uc/nFYWhWKJa6NTzagt4mi3bYallIm/nnNNsOqbpX2m1p1Cv0ctyVOwLKQ4iD5Kx5aMXjb7UB6doA1/8lhoLjfuuAKVN8gdN+jH6C/cOgvt9u5ZWHaR2K/9LPud37Uefu2P0rfFitWRKsrJG1XPcdbbZjG0fd9pDZ5nppOkBtALijHG/u1m/05a6WPdq8h3gj0HxZl7C3EgWB9Z26aBkzUYuoJB/310RUhrRnA4aFSNNNYviCBQY/B6B19qt8YiLFkFs5h3CiZqmJU3OjNci52FGZR5/vn/18djF7szhzzvfYAsLkuAWYqS8pF2GFe9zV5qESVjGF4BEVXhWw3HJbVbqL1AsLFfSNIAZlj8sjyFhgMT1TPlvDYWzHOdxlzBtxhr8f2WQwXymQ+Aw7N1pgg2ZG3c9eo6m9R1/9A0l5W4N5CwAA"; }
        }
    }
}
