// <auto-generated />
namespace Silversite.EntityTest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class EntityTest_v10 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205031553317_EntityTest_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XyW7bMBC9F+g/CLxHdNwiSAI5QWrHhdE6DqI0d1oa20QpShUpw/62HvpJ/YUOtS/eEuTQSxBRs7x5fDMj//39x7ndBMJaQ6x4KAfk3O4RC6QX+lwuByTRi7NLcnvz8YNz7wcb66Ww6xs79JRqQFZaR9eUKm8FAVN2wL04VOFC214YUOaHtN/rXdLzHgUMQTCWZTlPidQ8gPQBH4eh9CDSCRPT0Aeh8nN846ZRrQcWgIqYBwPicpHC1WDfYxC9fQal7SlfxkwjNkWsO8EZ4nJBLF4JsndlQJIyPQLIc2wjSEEMyCMmD2XdBq2+wbZxgEePcRhBrLdPsMg90YhYtOlI256lX93JpB+QidSf+sR6SIRgc4EHCyYUECu6uHZ1GMNXkIAkgP/ItIYYr2niQwo/p+E6ujiNiSva6xsmKJMy1CmvHeQtnOZvAdTVMcqHWGO+Af87yKVelWCnbFOcnPcvifVDclQbOuk4gXpx2fPhpMO0tlclvfj8qpwOrQTQlQXqVjOOrDe0YU5ho1sSyTxc0A1blGuVINOsnStsJ44yY9UiNOuRopfonmZypiyKkKFac+Unlpt11vDMfX2/BFkM6qkdbVOiLTOhTtkSWm8xNSId81jpEdNszsydDf2gY3YSv0WuJs3t9qxYL+zN/5nPsRFj75oBdUbHWGSArZfWCyWy3cMjd3U9Jli8q/uHoUgCuXeGHPLPurIeIDs5PULWYvUI2Uk3gkNb1bcppx3OW7OwfYWH9N82KbOXfdDSu5Nr7/iG6YgxMyEWUrPmvhGiu1UaAtsY2O4vMRQc660MpkzyBWrmOfwJZltir7x9LZXDWClf/K+7iZvyj26hzuo6fafINYu9FYu7G+TtK2NnTLMg3m8jdAfbKVvhwFLItFifUdWIwroy1OVueeMK6baKQ+ufbM4IFF9WIcwHnATPDMcqaGEzkYuwuAQstI6oMGnd0RQ085Gvu1jzBfM0vvZAqXS9vzCRoMl9MAd/ImeJjhJ9pxQEc9FQsEMP50/3ZBOzM4vS8f4eJSBMjiXATH5JuPBL3OOu7veFMNLJmwlR4ecNhltuy0gPoTwxUE7fCCKQphWfIYgEBlMz6bI17Md2nMMmY86IM9yRQZ3B7CRH4jLMXEuBCeoeVT7zi4Oanxw3/wBjVtxjpAwAAA=="; }
        }
    }
}
