// <auto-generated />
namespace Silversite.Migrations.MigrationHistory
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MigrationHistoryv10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigrationHistoryv10));
        
        string IMigrationMetadata.Id
        {
            get { return "201209031733434_MigrationHistory.v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
