// <auto-generated />
namespace Silversite.Migrations.Silversite
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Silversitev10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Silversitev10));
        
        string IMigrationMetadata.Id
        {
            get { return "201212200507485_Silversite.v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
